(function initEduPayPaymentsDB() {
  const catalog = [
    {
      id: "mobile",
      name: "Мобильная связь",
      description: "Пополнение телефона и оплата мобильных операторов.",
      providers: [
        {
          id: "mts",
          name: "МТС",
          maskLabel: "Номер телефона",
          placeholder: "+7 9XX XXX-XX-XX",
          pattern: "^\\+79\\d{9}$",
          formatHint: "Формат: +7 9XX XXX-XX-XX. Можно начать с + или с 9: префикс +7 добавится автоматически.",
          exampleHint: "Маска показывает формат ввода и сама по себе не проходит оплату.",
          inputType: "phone",
          validAccounts: ["+79001112233", "+79005551010", "+79007775500", "+79161234567"],
          feePercent: 2.5,
          minAmount: 100,
          maxAmount: 5000,
        },
        {
          id: "beeline",
          name: "Билайн",
          maskLabel: "Номер телефона",
          placeholder: "+7 9XX XXX-XX-XX",
          pattern: "^\\+79\\d{9}$",
          formatHint: "Формат: +7 9XX XXX-XX-XX. Можно начать с + или с 9: префикс +7 добавится автоматически.",
          exampleHint: "Маска показывает формат ввода и сама по себе не проходит оплату.",
          inputType: "phone",
          validAccounts: ["+79032224455", "+79035556677", "+79038889900"],
          feePercent: 2,
          minAmount: 100,
          maxAmount: 5000,
        },
      ],
    },
    {
      id: "internet",
      name: "Интернет",
      description: "Оплата домашнего интернета и цифровых сервисов.",
      providers: [
        {
          id: "rostelecom",
          name: "Ростелеком",
          maskLabel: "Номер договора",
          placeholder: "XXXXXXXXXX",
          pattern: "^\\d{8,12}$",
          formatHint: "Формат: 8-12 цифр без пробелов и дефисов.",
          exampleHint: "Подсказка показывает допустимую длину, но оплату принимает только зарегистрированный договор.",
          validAccounts: ["2400187621", "2400187622", "880045123001"],
          feePercent: 1.5,
          minAmount: 200,
          maxAmount: 10000,
        },
        {
          id: "domru",
          name: "Дом.ru",
          maskLabel: "Лицевой счет",
          placeholder: "XXXXXXXXX",
          pattern: "^\\d{9}$",
          formatHint: "Формат: 9 цифр без пробелов.",
          exampleHint: "Маска не является готовым лицевым счетом.",
          validAccounts: ["704118903", "704118904", "704118905"],
          feePercent: 1.8,
          minAmount: 200,
          maxAmount: 10000,
        },
      ],
    },
    {
      id: "utilities",
      name: "ЖКХ",
      description: "Коммунальные услуги и квартплата.",
      providers: [
        {
          id: "water",
          name: "Горводоканал",
          maskLabel: "Лицевой счет",
          placeholder: "XXXXXXXXXX",
          pattern: "^\\d{10}$",
          formatHint: "Формат: 10 цифр без пробелов.",
          exampleHint: "Подсказка показывает структуру номера, не готовый реквизит.",
          validAccounts: ["1200457788", "1200457799", "1200457800"],
          feePercent: 1.2,
          minAmount: 300,
          maxAmount: 15000,
        },
        {
          id: "power",
          name: "Энергосбыт",
          maskLabel: "Номер абонента",
          placeholder: "XXXXXXXX",
          pattern: "^\\d{6,10}$",
          formatHint: "Формат: 6-10 цифр без пробелов.",
          exampleHint: "Образец нужен только для ориентира по длине.",
          validAccounts: ["60244791", "60244792", "7710093456"],
          feePercent: 1,
          minAmount: 300,
          maxAmount: 15000,
        },
      ],
    },
    {
      id: "wallet",
      name: "Электронный кошелек",
      description: "Пополнение электронного кошелька по идентификатору.",
      providers: [
        {
          id: "eduwallet",
          name: "AirWallet",
          maskLabel: "Идентификатор кошелька",
          placeholder: "AW-XXXXXX",
          pattern: "^AW-\\d{6}$",
          formatHint: "Формат: AW-XXXXXX, где X - цифра.",
          exampleHint: "Маска показывает вид идентификатора, но принимаются только заведенные кошельки.",
          inputType: "wallet",
          validAccounts: ["AW-482916", "AW-571204", "AW-830115", "AW-204778"],
          feePercent: 0.8,
          minAmount: 100,
          maxAmount: 20000,
        },
      ],
    },
  ];

  window.EduPayPaymentsDB = { catalog };
})();
